# Generated by Django 6.0.7 on 2026-07-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_utilisateur_ligue'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Masculin / Monsieur'), ('F', 'Féminin / Madame')], default='M', max_length=1),
        ),
    ]
