# Generated by Django 6.0.6 on 2026-08-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_utilisateur_sexe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='nom_role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Administrateur'), ('GEST_LIGUE', 'Gestionnaire Ligue (Administrateur Principal / SG)'), ('GEST_TECHNIQUE', 'Responsable Technique Ligue (Examens, Grades)'), ('GEST_FINANCIER', 'Gestionnaire Financier Ligue'), ('GEST_COM', 'Chargé de Communication Ligue'), ('GEST_CLUB', 'Gestionnaire Club'), ('JURY', 'Membre du Jury / Évaluateur')], max_length=50, unique=True),
        ),
    ]
