# Generated by Django 4.2.30 on 2026-09-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_role_nom_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='permissions_accordees',
            field=models.ManyToManyField(blank=True, related_name='utilisateurs_accordees', to='accounts.permission', verbose_name='Permissions accordées spécifiquement'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='permissions_refusees',
            field=models.ManyToManyField(blank=True, related_name='utilisateurs_refusees', to='accounts.permission', verbose_name='Permissions révoquées spécifiquement'),
        ),
        migrations.AlterField(
            model_name='role',
            name='nom_role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Administrateur'), ('GEST_LIGUE', 'Gestionnaire Ligue'), ('GEST_TECHNIQUE', 'Responsable Technique'), ('GEST_FINANCIER', 'Gestionnaire Financier'), ('GEST_COM', 'Chargé de Communication'), ('GEST_CLUB', 'Gestionnaire Club'), ('JURY', 'Membre du Jury')], max_length=50, unique=True),
        ),
    ]
