# Generated by Django 6.0.6 on 2026-06-24 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('ordre', models.PositiveSmallIntegerField(help_text='Ordre croissant : 1 = plus bas, 6 = plus haut', unique=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Pratiquant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('lieu_naissance', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pratiquants/')),
                ('actif', models.BooleanField(default=True)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pratiquants', to='clubs.club')),
                ('grade_actuel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pratiquants', to='practitioners.grade')),
            ],
            options={
                'verbose_name': 'Pratiquant',
                'verbose_name_plural': 'Pratiquants',
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
