# Generated by Django 6.0.6 on 2026-06-26 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligues', '0004_remove_ligue_contact_secretaire_and_more'),
        ('practitioners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='ligue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='ligues.ligue'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='nom',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='grade',
            name='ordre',
            field=models.PositiveSmallIntegerField(help_text='Ordre croissant : 1 = plus bas, 6 = plus haut'),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('ligue', 'nom'), ('ligue', 'ordre')},
        ),
    ]
