# Generated by Django 6.0.6 on 2026-06-26 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ligues', '0004_remove_ligue_contact_secretaire_and_more'),
        ('practitioners', '0002_grade_par_ligue'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('ligue', 'nom')},
        ),
    ]
