# Generated by Django 6.0.6 on 2026-06-27 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practitioners', '0004_grade_nom_non_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='pratiquant',
            name='matricule',
            field=models.CharField(blank=True, help_text="Attribué automatiquement lors de l'autorisation", max_length=20, null=True, unique=True),
        ),
    ]
