# Generated by Django 6.0.6 on 2026-06-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practitioners', '0006_grade_id_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='ordre',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Ordre croissant en chiffre romain (optionnel)', null=True),
        ),
    ]
