# Generated by Django 6.0.6 on 2026-06-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practitioners', '0007_grade_ordre_nullable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': [models.OrderBy(models.F('ordre'), nulls_last=True)], 'verbose_name': 'Grade', 'verbose_name_plural': 'Grades'},
        ),
    ]
