# Generated by Django 6.0.6 on 2026-06-29 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practitioners', '0008_add_date_limite_paiement_cascade_inscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['id_grade'], 'verbose_name': 'Grade', 'verbose_name_plural': 'Grades'},
        ),
        migrations.RemoveField(
            model_name='grade',
            name='ordre',
        ),
    ]
