# Generated by Django 6.0.6 on 2026-06-29 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practitioners', '0009_remove_ordre_from_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pratiquant',
            name='grade_actuel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pratiquants', to='practitioners.grade'),
        ),
    ]
