# Generated by Django 6.0.6 on 2026-07-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practitioners', '0010_grade_actuel_set_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='pratiquant',
            name='bulletin_grade',
            field=models.FileField(blank=True, help_text='Requis si le grade actuel est ≥ 2ème grade', null=True, upload_to='bulletins_grade/', verbose_name='Bulletin / attestation de grade'),
        ),
    ]
