# Generated by Django 6.0.7 on 2026-08-04 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practitioners', '0011_pratiquant_bulletin_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pratiquant',
            options={'ordering': ['grade_actuel__id_grade', 'nom', 'prenom'], 'verbose_name': 'Pratiquant', 'verbose_name_plural': 'Pratiquants'},
        ),
    ]
