# Generated by Django 6.0.6 on 2026-08-10 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practitioners', '0012_alter_pratiquant_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pratiquant',
            options={'ordering': ['grade_actuel__id_grade', 'nom', 'prenom'], 'verbose_name': 'Licencié', 'verbose_name_plural': 'Licenciés'},
        ),
    ]
