# Generated by Django 6.0.7 on 2026-08-17 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practitioners', '0013_alter_pratiquant_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriquePassageGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_passage', models.DateField(blank=True, help_text='Date à laquelle le passage de grade a eu lieu', null=True, verbose_name='Date du passage')),
                ('grade_libelle', models.CharField(help_text='Grade visé ou obtenu (ex : JAUNE, BLEUE, ROUGE...)', max_length=100, verbose_name='Grade')),
                ('moyenne', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Moyenne sur 20')),
                ('rang', models.CharField(blank=True, default='—', help_text='Ex : 1er, 3 Ex, 5è...', max_length=30, verbose_name='Rang')),
                ('mention', models.CharField(blank=True, default='—', help_text='Ex : Bien, Passable, Assez-bien...', max_length=50, verbose_name='Mention')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('pratiquant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_passages', to='practitioners.pratiquant')),
            ],
            options={
                'verbose_name': 'Historique de passage de grade',
                'verbose_name_plural': 'Historiques de passage de grade',
                'ordering': ['-date_passage', '-date_ajout'],
            },
        ),
    ]
