# Generated by Django 4.2.30 on 2026-09-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practitioners", "0014_historiquepassagegrade"),
    ]

    operations = [
        migrations.AddField(
            model_name="grade",
            name="est_grade_ligue",
            field=models.BooleanField(
                default=False,
                help_text="Si coché, ce grade est officiel Ligue (>= ROUGE) et exige un bulletin justificatif si le licencié est inscrit directement à ce niveau.",
                verbose_name="Grade officiel Ligue (>= ROUGE)",
            ),
        ),
    ]
