# Generated by Django 4.2.30 on 2026-09-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practitioners', '0015_grade_est_grade_ligue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['ordre', 'id_grade'], 'verbose_name': 'Grade', 'verbose_name_plural': 'Grades'},
        ),
        migrations.AddField(
            model_name='grade',
            name='ordre',
            field=models.PositiveIntegerField(default=0, help_text="Ordre de classement pour l'affichage des grades", verbose_name="Ordre d'affichage"),
        ),
    ]
