# Generated by Django 4.2.30 on 2026-10-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practitioners', '0017_fix_grade_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='ordre',
            field=models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage"),
        ),
    ]
