# Generated by Django 6.0.6 on 2026-06-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ligue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ligue', models.CharField(max_length=200)),
                ('sigle', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=100)),
                ('adresse_siege', models.CharField(blank=True, max_length=200)),
                ('email_contact', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('nom_directeur_adm', models.CharField(blank=True, max_length=100)),
                ('nom_directeur_tech', models.CharField(blank=True, max_length=100)),
                ('nom_secretaire', models.CharField(blank=True, max_length=100)),
                ('contact_secretaire', models.CharField(blank=True, max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='ligues/')),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('date_creation', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ligue',
                'verbose_name_plural': 'Ligues',
            },
        ),
    ]
