# Generated by Django 6.0.6 on 2026-06-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligue',
            name='nom_ligue',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='ligue',
            name='sigle',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
