# Generated by Django 6.0.6 on 2026-06-25 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligues', '0002_alter_ligue_nom_ligue_alter_ligue_sigle'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoletOrganigramme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_volet', models.CharField(max_length=200)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('ligue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volets', to='ligues.ligue')),
            ],
            options={
                'verbose_name': 'Volet organigramme',
                'verbose_name_plural': 'Volets organigramme',
                'ordering': ['ordre', 'date_creation'],
            },
        ),
        migrations.CreateModel(
            name='MembreOrganigramme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=50)),
                ('fonction', models.CharField(max_length=200)),
                ('actif', models.BooleanField(default=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('volet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='ligues.voletorganigramme')),
            ],
            options={
                'verbose_name': 'Membre organigramme',
                'verbose_name_plural': 'Membres organigramme',
                'ordering': ['-actif', 'nom', 'prenom'],
            },
        ),
    ]
