# Generated by Django 6.0.6 on 2026-06-25 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ligues', '0003_voletorganigramme_membreorganigramme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ligue',
            name='contact_secretaire',
        ),
        migrations.RemoveField(
            model_name='ligue',
            name='nom_directeur_adm',
        ),
        migrations.RemoveField(
            model_name='ligue',
            name='nom_directeur_tech',
        ),
        migrations.RemoveField(
            model_name='ligue',
            name='nom_secretaire',
        ),
    ]
