# Generated by Django 6.0.7 on 2026-07-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligues', '0005_membreorganigramme_date_debut_fonction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membreorganigramme',
            name='fonction',
            field=models.CharField(choices=[('PDT', 'Présidente'), ('VPT', 'Vice-Président'), ('SG', 'Secrétaire Général'), ('SGA', 'Secrétaire Général Adjoint'), ('TG', 'Trésorière Générale'), ('TA', 'Trésorière Adjointe'), ('SO', "Secrétaire à l'Organisation"), ('SAO', "Secrétaire Adjoint à l'Organisation"), ('SIC', "Secrétaire à l'Information et à la Communication"), ('CC1', '1er Commissaire aux Comptes'), ('CC2', '2e Commissaire aux Comptes'), ('CJ', 'Conseiller Juridique'), ('DT', 'Directeur Technique'), ('DTA', 'Directeur Technique Adjoint'), ('ENT', "Entraîneur de l'Équipe de la Ligue")], max_length=200),
        ),
    ]
