# Generated by Django 6.0.7 on 2026-08-04 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_parametresaffiliation'),
        ('ligues', '0006_alter_membreorganigramme_fonction'),
    ]

    operations = [
        migrations.AddField(
            model_name='membreorganigramme',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membres_organigramme', to='clubs.club'),
        ),
        migrations.AlterField(
            model_name='membreorganigramme',
            name='fonction',
            field=models.CharField(max_length=200),
        ),
    ]
