# Generated by Django 6.0.7 on 2026-08-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligues', '0007_membreorganigramme_club_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligue',
            name='historique',
            field=models.TextField(blank=True, verbose_name='Historique du Wushu dans la région'),
        ),
        migrations.AddField(
            model_name='ligue',
            name='mot_president',
            field=models.TextField(blank=True, verbose_name='Mot du Président'),
        ),
        migrations.AddField(
            model_name='ligue',
            name='nom_president',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nom & Titre du Président'),
        ),
        migrations.AddField(
            model_name='ligue',
            name='objectif_general',
            field=models.TextField(blank=True, verbose_name='Objectif général'),
        ),
        migrations.AddField(
            model_name='ligue',
            name='objectifs_specifiques',
            field=models.TextField(blank=True, verbose_name='Objectifs spécifiques'),
        ),
        migrations.AddField(
            model_name='ligue',
            name='photo_president',
            field=models.ImageField(blank=True, null=True, upload_to='ligues/president/', verbose_name='Photo du Président'),
        ),
        migrations.AddField(
            model_name='ligue',
            name='presentation_generale',
            field=models.TextField(blank=True, verbose_name='Présentation générale'),
        ),
        migrations.AddField(
            model_name='ligue',
            name='valeurs',
            field=models.TextField(blank=True, verbose_name='Valeurs fondamentales'),
        ),
        migrations.AddField(
            model_name='ligue',
            name='vision',
            field=models.TextField(blank=True, verbose_name='Vision stratégique'),
        ),
    ]
