# Generated by Django 6.0.7 on 2026-08-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligues', '0008_ligue_historique_ligue_mot_president_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligue',
            name='titre_contact',
            field=models.CharField(blank=True, default='Contact & Localisation', max_length=100, verbose_name='Titre du bouton Contact'),
        ),
        migrations.AddField(
            model_name='ligue',
            name='titre_mot_president',
            field=models.CharField(blank=True, default='Mot du Président', max_length=100, verbose_name='Titre du bouton Mot du Président / Présidente'),
        ),
        migrations.AddField(
            model_name='ligue',
            name='titre_organigramme',
            field=models.CharField(blank=True, default='Organigramme & Direction', max_length=100, verbose_name='Titre du bouton Organigramme'),
        ),
        migrations.AddField(
            model_name='ligue',
            name='titre_presentation',
            field=models.CharField(blank=True, default='Présentation de la Ligue', max_length=100, verbose_name='Titre du bouton Présentation'),
        ),
        migrations.AddField(
            model_name='ligue',
            name='titre_vision_missions',
            field=models.CharField(blank=True, default='Vision & Missions', max_length=100, verbose_name='Titre du bouton Vision & Missions'),
        ),
        migrations.AlterField(
            model_name='ligue',
            name='mot_president',
            field=models.TextField(blank=True, verbose_name='Mot du Président / de la Présidente'),
        ),
    ]
