# Generated by Django 6.0.7 on 2026-08-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligues', '0009_ligue_titre_contact_ligue_titre_mot_president_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligue',
            name='bulletin_header_droite_devise',
            field=models.CharField(blank=True, default='La Patrie ou la Mort, nous Vaincrons', max_length=150, verbose_name='En-tête droite - Devise'),
        ),
        migrations.AddField(
            model_name='ligue',
            name='bulletin_header_droite_ligne1',
            field=models.CharField(blank=True, default='BURKINA FASO', max_length=150, verbose_name='En-tête droite - Pays'),
        ),
        migrations.AddField(
            model_name='ligue',
            name='bulletin_header_gauche_ligne1',
            field=models.CharField(blank=True, default='FEDERATION BURKINABE DE KUNG FU WUSHU (FBKFW)', max_length=200, verbose_name='En-tête gauche - Ligne 1 (Fédération)'),
        ),
        migrations.AddField(
            model_name='ligue',
            name='bulletin_header_gauche_ligne2',
            field=models.CharField(blank=True, default='LIGUE DU KADIOGO DE KUNG FU WUSHU (LKKFW)', max_length=200, verbose_name='En-tête gauche - Ligne 2 (Ligue)'),
        ),
        migrations.AddField(
            model_name='ligue',
            name='bulletin_mention_exemplaire',
            field=models.CharField(blank=True, default="Ceci est un document original, il n'est délivré qu'en un seul exemplaire.", max_length=200, verbose_name="Mention d'exemplaire unique (bas de page)"),
        ),
        migrations.AddField(
            model_name='ligue',
            name='bulletin_pied_legal',
            field=models.TextField(blank=True, default='LIGUE DU KADIOGO DE KUNG FU WUSHU (LKKFW)\nSiège social : Ouagadougou, Récépissé n° : 2024-22/MSJE/RCEN/DRSL-CEN/SRRIS\nMail : ligueducentrekungfuwushu@gmail.com Tél : (+226) 65 08 92 62 / 73 86 86 16', verbose_name='Pied de page légal du bulletin'),
        ),
        migrations.AddField(
            model_name='ligue',
            name='bulletin_signataire_grade',
            field=models.CharField(blank=True, default='CN 3è Duan', max_length=100, verbose_name='Grade/Titre du signataire'),
        ),
        migrations.AddField(
            model_name='ligue',
            name='bulletin_signataire_nom',
            field=models.CharField(blank=True, default='Pr Issa BOUSSIM', max_length=150, verbose_name='Nom du signataire'),
        ),
        migrations.AddField(
            model_name='ligue',
            name='bulletin_signataire_titre',
            field=models.CharField(blank=True, default='Directeur Technique', max_length=100, verbose_name='Titre du signataire'),
        ),
    ]
