# Generated by Django 6.0.6 on 2026-08-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligues', '0010_ligue_bulletin_header_droite_devise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligue',
            name='titre_contact',
            field=models.CharField(blank=True, default='Contact', max_length=100, verbose_name='Titre du bouton Contact'),
        ),
    ]
