# Generated by Django 6.0.6 on 2026-08-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligues', '0011_alter_ligue_titre_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membreorganigramme',
            options={'ordering': ['-actif', 'ordre', 'nom', 'prenom'], 'verbose_name': 'Membre organigramme', 'verbose_name_plural': 'Membres organigramme'},
        ),
        migrations.AddField(
            model_name='membreorganigramme',
            name='ordre',
            field=models.PositiveIntegerField(default=1, help_text='Numéro de ligne : 1 = Ligne du haut (Président), 2 = Ligne du dessous (VP), 3 = Ligne 3...', verbose_name='Ligne / Rang hiérarchique'),
        ),
    ]
