# Generated by Django 6.0.6 on 2026-08-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligues', '0012_alter_membreorganigramme_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligue',
            name='phrases_hero_accueil',
            field=models.TextField(blank=True, default='Gestion des passages de grades sportifs\nAffiliations et Licences des Clubs\nRégularisation et Homologation des Ceintures\nPromotion et Développement du Wushu', help_text="Entrez les phrases d'animation de la bannière d'accueil (une phrase par ligne).", verbose_name="Phrases dynamiques de l'Accueil (1 par ligne)"),
        ),
    ]
