# Generated by Django 6.0.6 on 2026-08-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligues', '0013_ligue_phrases_hero_accueil'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligue',
            name='soustitre_hero_accueil',
            field=models.TextField(blank=True, default="Suivez chaque parcours, du club jusqu'au grade obtenu, en toute transparence", verbose_name="Sous-titre de la Bannière d'Accueil"),
        ),
        migrations.AddField(
            model_name='ligue',
            name='titre_hero_accueil',
            field=models.CharField(blank=True, default='Une seule plateforme pour toutes les ligues et fédérations', max_length=250, verbose_name="Titre principal de la Bannière d'Accueil"),
        ),
        migrations.AlterField(
            model_name='ligue',
            name='phrases_hero_accueil',
            field=models.TextField(blank=True, default='Gestion des passages de grades sportifs\nAffiliations et Licences des Clubs\nRégularisation et Homologation des Ceintures\nPromotion et Développement du Wushu', help_text="Entrez les phrases d'animation de la bannière d'accueil (une phrase par ligne).", verbose_name='Phrases dynamiques tournantes (1 par ligne)'),
        ),
    ]
