# Generated by Django 6.0.6 on 2026-08-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligues', '0014_ligue_soustitre_hero_accueil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligue',
            name='titre_hero_accueil',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Titre principal fixe de la Bannière (Optionnel)'),
        ),
    ]
