# Generated by Django 6.0.7 on 2026-08-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligues', '0015_alter_ligue_titre_hero_accueil'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligue',
            name='lien_facebook',
            field=models.URLField(blank=True, default='https://facebook.com', max_length=300, verbose_name='Lien Facebook Officiel'),
        ),
        migrations.AddField(
            model_name='ligue',
            name='lien_whatsapp',
            field=models.CharField(blank=True, default='https://wa.me/22673868616', max_length=200, verbose_name='Lien / Numéro WhatsApp'),
        ),
        migrations.AddField(
            model_name='ligue',
            name='lien_youtube',
            field=models.URLField(blank=True, default='https://youtube.com', max_length=300, verbose_name='Lien YouTube Officiel'),
        ),
    ]
