# Generated by Django 6.0.7 on 2026-08-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligues', '0016_ligue_lien_facebook_ligue_lien_whatsapp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligue',
            name='lien_facebook',
            field=models.URLField(blank=True, default='https://facebook.com/lkkfw', max_length=300, verbose_name='Lien Facebook Officiel'),
        ),
    ]
