# Generated by Django 4.2.30 on 2026-09-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligues', '0017_alter_ligue_lien_facebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligue',
            name='bulletin_prefixe_securite',
            field=models.CharField(blank=True, default='LK-BUL', max_length=30, verbose_name='Préfixe du Code de Sécurité / Authentification (ex: LK-BUL)'),
        ),
    ]
