# Generated by Django 6.0.6 on 2026-06-24 16:02

import apps.clubs.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('ligues', '0002_alter_ligue_nom_ligue_alter_ligue_sigle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_club', models.CharField(max_length=200)),
                ('sigle_club', models.CharField(blank=True, max_length=20)),
                ('localite', models.CharField(max_length=100)),
                ('adresse', models.CharField(blank=True, max_length=200)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('maitre_club', models.CharField(blank=True, max_length=100)),
                ('contact_maitre', models.CharField(blank=True, max_length=20)),
                ('responsable_club', models.CharField(blank=True, max_length=100)),
                ('contact_responsable', models.CharField(blank=True, max_length=20)),
                ('statut_club', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('AFFILIE', 'Affilié'), ('SUSPENDU', 'Suspendu'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=20)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('ligue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clubs', to='ligues.ligue')),
                ('utilisateur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='club', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubs',
                'ordering': ['nom_club'],
            },
        ),
        migrations.CreateModel(
            name='DemandeAffiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('montant_frais', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut_affiliation', models.CharField(choices=[('EN_ATTENTE_PAIEMENT', 'En attente de paiement'), ('EN_ATTENTE_VALID_FINANCIER', 'En attente validation financier'), ('EN_ATTENTE_VALID_LIGUE', 'En attente validation ligue'), ('APPROUVEE', 'Approuvée'), ('REJETEE', 'Rejetée — modification possible')], default='EN_ATTENTE_PAIEMENT', max_length=40)),
                ('motif_rejet', models.TextField(blank=True)),
                ('nombre_soumissions', models.PositiveSmallIntegerField(default=0)),
                ('annee_sportive', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_affiliation', to='exams.anneesportive')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_affiliation', to='clubs.club')),
            ],
            options={
                'verbose_name': "Demande d'affiliation",
                'verbose_name_plural': "Demandes d'affiliation",
                'ordering': ['-date_demande'],
                'unique_together': {('club', 'annee_sportive')},
            },
        ),
        migrations.CreateModel(
            name='PieceJustificativeAffiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_piece', models.CharField(choices=[('STATUTS', 'Statuts du club'), ('RECEPISSE', 'Récépissé officiel'), ('LISTE', 'Liste des membres fondateurs'), ('AUTRE', 'Autre document')], default='AUTRE', max_length=20)),
                ('fichier', models.FileField(help_text='Formats acceptés : PDF, JPG, PNG (max 5 Mo)', upload_to=apps.clubs.models.chemin_piece_affiliation)),
                ('nom_fichier', models.CharField(blank=True, max_length=200)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_justificatives', to='clubs.demandeaffiliation')),
            ],
            options={
                'verbose_name': 'Pièce justificative',
                'verbose_name_plural': 'Pièces justificatives',
            },
        ),
    ]
