# Generated by Django 6.0.6 on 2026-06-25 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='contact_maitre',
        ),
        migrations.RemoveField(
            model_name='club',
            name='contact_responsable',
        ),
        migrations.RemoveField(
            model_name='club',
            name='maitre_club',
        ),
        migrations.RemoveField(
            model_name='club',
            name='responsable_club',
        ),
        migrations.CreateModel(
            name='VoletOrganigrammeClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_volet', models.CharField(max_length=200)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volets', to='clubs.club')),
            ],
            options={
                'verbose_name': 'Volet organigramme club',
                'verbose_name_plural': 'Volets organigramme club',
                'ordering': ['ordre', 'date_creation'],
            },
        ),
        migrations.CreateModel(
            name='MembreOrganigrammeClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=50)),
                ('fonction', models.CharField(max_length=200)),
                ('actif', models.BooleanField(default=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('volet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='clubs.voletorganigrammeclub')),
            ],
            options={
                'verbose_name': 'Membre organigramme club',
                'verbose_name_plural': 'Membres organigramme club',
                'ordering': ['-actif', 'nom', 'prenom'],
            },
        ),
    ]
