# Generated by Django 6.0.6 on 2026-07-12 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_membreorganigrammeclub_date_debut_fonction'),
        ('ligues', '0005_membreorganigramme_date_debut_fonction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresAffiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_frais_affiliation', models.DecimalField(decimal_places=2, default=0, help_text="Montant des frais d'affiliation dus par un club (FCFA)", max_digits=10)),
                ('ligue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametres_affiliation', to='ligues.ligue')),
            ],
            options={
                'verbose_name': "Paramètres d'affiliation",
                'verbose_name_plural': "Paramètres d'affiliation",
            },
        ),
    ]
