# Generated by Django 6.0.7 on 2026-08-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_parametresaffiliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='code_club',
            field=models.CharField(blank=True, help_text='Généré automatiquement (ex : CL01, CL02...) si laissé vide.', max_length=20, null=True, verbose_name='Code unique du club'),
        ),
    ]
