# Generated by Django 6.0.7 on 2026-08-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_club_code_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='nom_fondateur',
            field=models.CharField(blank=True, help_text='Nom du Maître principal / Fondateur du club', max_length=200, verbose_name='Maître / Fondateur du club'),
        ),
    ]
