# Generated by Django 6.0.7 on 2026-08-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_club_nom_fondateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Coordonnée latitude (ex: 12.3714)', null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='club',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Coordonnée longitude (ex: -1.5197)', null=True, verbose_name='Longitude'),
        ),
    ]
