# Generated by Django 6.0.7 on 2026-08-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_club_latitude_club_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='description',
            field=models.TextField(blank=True, help_text="Présentation courte du club pour l'annuaire public", verbose_name='Description / Présentation du club'),
        ),
    ]
