# Generated by Django 6.0.6 on 2026-08-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_club_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membreorganigrammeclub',
            options={'ordering': ['-actif', 'ordre', 'nom', 'prenom'], 'verbose_name': 'Membre organigramme club', 'verbose_name_plural': 'Membres organigramme club'},
        ),
        migrations.AddField(
            model_name='membreorganigrammeclub',
            name='ordre',
            field=models.PositiveIntegerField(default=1, help_text='Numéro de ligne : 1 = Ligne du haut (Président), 2 = Ligne du dessous (VP), 3 = Ligne 3...', verbose_name='Ligne / Rang hiérarchique'),
        ),
    ]
