# Generated by Django 6.0.6 on 2026-08-11 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_alter_membreorganigrammeclub_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeaffiliation',
            name='approuve_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_affiliation_approuvees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demandeaffiliation',
            name='date_approbation',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'approbation"),
        ),
    ]
