# Generated by Django 6.0.6 on 2026-08-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0012_alter_club_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='date_delivrance_recepisse',
            field=models.DateField(blank=True, null=True, verbose_name='Date de délivrance du récépissé'),
        ),
        migrations.AddField(
            model_name='club',
            name='date_expiration_recepisse',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'expiration du récépissé (si connue)"),
        ),
        migrations.AddField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo ou blason du club (PNG, JPG)', null=True, upload_to='clubs/logos/', verbose_name='Logo officiel du club'),
        ),
        migrations.AddField(
            model_name='club',
            name='loi_reglementation',
            field=models.CharField(blank=True, default='Loi N° 064-2015/CNT', max_length=200, verbose_name='Loi / Réglementation régissante'),
        ),
        migrations.AddField(
            model_name='club',
            name='numero_recepisse',
            field=models.CharField(blank=True, help_text='Ex : N° 2024-22/MSJE/RCEN/DRSL-CEN/SRRIS', max_length=150, verbose_name="Numéro du récépissé d'existence"),
        ),
        migrations.AddField(
            model_name='parametresaffiliation',
            name='duree_validite_recepisse_ans',
            field=models.PositiveSmallIntegerField(default=3, help_text="Nombre d'années de validité d'un récépissé d'existence après délivrance.", verbose_name='Durée de validité par défaut du récépissé (en années)'),
        ),
        migrations.AddField(
            model_name='parametresaffiliation',
            name='exiger_recepisse_valide',
            field=models.BooleanField(default=False, help_text="Si coché, les clubs doivent obligatoirement fournir le numéro et la date de leur récépissé d'existence.", verbose_name='Exiger la saisie obligatoire du récépissé lors des affiliations'),
        ),
        migrations.AlterField(
            model_name='club',
            name='nom_fondateur',
            field=models.CharField(blank=True, help_text='Nom du Maître principal du club', max_length=200, verbose_name='Maître du club'),
        ),
    ]
