# Generated by Django 6.0.6 on 2026-08-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0013_club_date_delivrance_recepisse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametresaffiliation',
            name='attestation_nom_signataire',
            field=models.CharField(default='Le Président de la Ligue', help_text='Ex: Nom complet ou fonction officielle', max_length=150, verbose_name='Nom / Qualité du signataire'),
        ),
        migrations.AddField(
            model_name='parametresaffiliation',
            name='attestation_texte_conclusion',
            field=models.TextField(default='En foi de quoi, cette attestation lui est délivrée pour servir et valoir ce que de droit, lui conférant la pleine légitimité de participer aux championnats, stages, passages de grades et activités officiels organisés par la Ligue.', help_text="Paragraphe final de l'attestation", verbose_name='Texte de conclusion / attribution des droits'),
        ),
        migrations.AddField(
            model_name='parametresaffiliation',
            name='attestation_texte_introduction',
            field=models.TextField(default="certifie par la présente que l'association sportive ci-après nommée :", help_text="Texte d'introduction certifiant l'affiliation", verbose_name="Texte d'introduction / certification"),
        ),
        migrations.AddField(
            model_name='parametresaffiliation',
            name='attestation_texte_sceau',
            field=models.CharField(default='SCEAU OFFICIEL DE LA LIGUE', help_text='Texte figurant dans le sceau', max_length=150, verbose_name='Texte du sceau / cachet officiel'),
        ),
        migrations.AddField(
            model_name='parametresaffiliation',
            name='attestation_titre',
            field=models.CharField(default="ATTESTATION D'AFFILIATION", help_text="Ex: ATTESTATION D'AFFILIATION", max_length=150, verbose_name='Titre principal du document'),
        ),
        migrations.AddField(
            model_name='parametresaffiliation',
            name='attestation_titre_signataire',
            field=models.CharField(default='Pour le Bureau Exécutif, Le Président de la Ligue', help_text='Ex: Pour le Bureau Exécutif, Le Président de la Ligue', max_length=150, verbose_name='Titre du signataire'),
        ),
        migrations.AddField(
            model_name='parametresaffiliation',
            name='attestation_ville_delivrance',
            field=models.CharField(default='Fait à Ouagadougou, le', help_text='Ex: Fait à Ouagadougou, le', max_length=100, verbose_name='Formule de lieu de délivrance'),
        ),
    ]
