# Generated by Django 6.0.6 on 2026-08-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0014_parametresaffiliation_attestation_nom_signataire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametresaffiliation',
            name='attestation_devise',
            field=models.CharField(default='Unité - Progrès - Justice', help_text='Ex: Unité - Progrès - Justice', max_length=150, verbose_name='Devise nationale / Slogan'),
        ),
        migrations.AddField(
            model_name='parametresaffiliation',
            name='attestation_pays',
            field=models.CharField(default='BURKINA FASO', help_text='Ex: BURKINA FASO', max_length=100, verbose_name='Nom du Pays / En-tête supérieur'),
        ),
        migrations.AddField(
            model_name='parametresaffiliation',
            name='attestation_prefixe_enregistrement',
            field=models.CharField(default="N° d'enregistrement :", help_text="Ex: N° d'enregistrement :", max_length=100, verbose_name="Intitulé du numéro d'enregistrement"),
        ),
        migrations.AddField(
            model_name='parametresaffiliation',
            name='attestation_sous_titre_ligue',
            field=models.CharField(default='Ligue du Kadiogo de Kung-Fu Wushu', help_text='Ex: Ligue du Kadiogo de Kung-Fu Wushu', max_length=150, verbose_name="Nom complet / Titre de la Ligue dans l'en-tête"),
        ),
    ]
