# Generated by Django 6.0.6 on 2026-08-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0015_parametresaffiliation_attestation_devise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametresaffiliation',
            name='attestation_sigle_ligue',
            field=models.CharField(default='LKKFW', help_text='Ex: LKKFW', max_length=50, verbose_name='Sigle / Acronyme de la Ligue (ex: LKKFW)'),
        ),
    ]
