# Generated by Django 6.0.6 on 2026-06-24 17:35

import apps.payments.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        ('exams', '0002_rubrique_sessionexamen_rubriquegrade_inscription_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementAffiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_paye', models.DecimalField(decimal_places=2, help_text='Montant indiqué sur la preuve de paiement', max_digits=10)),
                ('reference', models.CharField(blank=True, help_text='Numéro de reçu ou référence de la transaction', max_length=100)),
                ('fichier_preuve', models.FileField(help_text='Reçu de paiement (PDF, JPG, PNG)', upload_to=apps.payments.models.chemin_preuve_affiliation)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de vérification'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=15)),
                ('motif_rejet', models.TextField(blank=True)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='clubs.demandeaffiliation')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_affiliation_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Paiement d'affiliation",
                'verbose_name_plural': "Paiements d'affiliation",
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.CreateModel(
            name='PaiementExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_paye', models.DecimalField(decimal_places=2, help_text='Montant total payé pour tous les pratiquants', max_digits=10)),
                ('montant_attendu', models.DecimalField(decimal_places=2, default=0, help_text='Calculé automatiquement (somme des tarifs des inscrits)', max_digits=10)),
                ('reference', models.CharField(blank=True, help_text='Numéro de reçu ou référence de la transaction', max_length=100)),
                ('fichier_preuve', models.FileField(help_text='Reçu de paiement (PDF, JPG, PNG)', upload_to=apps.payments.models.chemin_preuve_examen)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de vérification'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=15)),
                ('motif_rejet', models.TextField(blank=True)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements_examen', to='clubs.club')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='exams.sessionexamen')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_examen_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Paiement d'examen",
                'verbose_name_plural': "Paiements d'examen",
                'ordering': ['-date_soumission'],
                'unique_together': {('club', 'session')},
            },
        ),
    ]
