# Generated by Django 6.0.6 on 2026-06-29 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paiementexamen',
            unique_together=set(),
        ),
    ]
