# Generated by Django 6.0.6 on 2026-06-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_paiementexamen_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementexamen',
            name='mode_paiement',
            field=models.CharField(choices=[('DEPOT_MOBILE', 'Dépôt mobile (Orange Money, Moov Money…)'), ('ESPECES', 'Espèces')], default='DEPOT_MOBILE', help_text='Mode de règlement utilisé', max_length=15),
        ),
        migrations.AddField(
            model_name='paiementexamen',
            name='numero_beneficiaire',
            field=models.CharField(blank=True, help_text='Numéro du bénéficiaire (dépôt mobile)', max_length=50),
        ),
        migrations.AddField(
            model_name='paiementexamen',
            name='numero_expediteur',
            field=models.CharField(blank=True, help_text="Numéro de l'expéditeur (dépôt mobile — optionnel)", max_length=50),
        ),
    ]
