# Generated by Django 6.0.6 on 2026-06-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_add_mode_paiement_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementexamen',
            name='nom_payeur',
            field=models.CharField(blank=True, help_text='Nom de la personne qui a effectué le paiement en espèces', max_length=100),
        ),
        migrations.AlterField(
            model_name='paiementexamen',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente de vérification'), ('INSUFFISANT', 'Insuffisant — complément demandé'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=15),
        ),
    ]
