# Generated by Django 6.0.6 on 2026-06-30 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_add_nom_payeur_insuffisant_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriquePaiementExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SOUMIS', 'Preuve soumise'), ('RESOUMIS', 'Preuve resoumise'), ('VALIDE', 'Paiement validé'), ('REJETE', 'Preuve rejetée'), ('INSUFFISANT', 'Montant insuffisant')], max_length=15)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('motif', models.TextField(blank=True)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('acteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique_paiements_examen', to=settings.AUTH_USER_MODEL)),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='payments.paiementexamen')),
            ],
            options={
                'verbose_name': 'Historique paiement examen',
                'verbose_name_plural': 'Historique paiements examen',
                'ordering': ['-date_action'],
            },
        ),
    ]
