# Generated by Django 6.0.6 on 2026-06-24 17:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0002_rubrique_sessionexamen_rubriquegrade_inscription_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteRubrique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(decimal_places=2, help_text='Note sur 20', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('validee', models.BooleanField(default=False, help_text='Une note validée ne peut plus être modifiée')),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='exams.inscription')),
                ('jury', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes_saisies', to=settings.AUTH_USER_MODEL)),
                ('rubrique_grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='exams.rubriquegrade')),
            ],
            options={
                'verbose_name': 'Note par rubrique',
                'verbose_name_plural': 'Notes par rubrique',
                'ordering': ['inscription', 'rubrique_grade__rubrique__nom'],
                'unique_together': {('inscription', 'rubrique_grade')},
            },
        ),
    ]
