# Generated by Django 6.0.6 on 2026-06-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noterubrique',
            name='correction_demandee',
            field=models.BooleanField(default=False, help_text='Le jury a demandé une autorisation de correction au Gestionnaire Ligue'),
        ),
    ]
