# Generated by Django 6.0.6 on 2026-07-10 15:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0003_noterubrique_jury_vers_affectation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noterubrique',
            name='note',
            field=models.DecimalField(decimal_places=2, help_text='Note sur 5', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
