# Generated by Django 6.0.6 on 2026-06-24 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        ('ligues', '0002_alter_ligue_nom_ligue_alter_ligue_sigle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('LIGUE', 'Ligue'), ('CLUB', 'Club')], max_length=10)),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='actualites/')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE', 'En attente de validation'), ('PUBLIEE', 'Publiée'), ('REJETEE', 'Rejetée')], default='BROUILLON', max_length=15)),
                ('motif_rejet', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actualites_redigees', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(blank=True, help_text="Renseigné uniquement si l'actualité vient d'un club", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actualites', to='clubs.club')),
                ('ligue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actualites', to='ligues.ligue')),
                ('validee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actualites_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type_document', models.CharField(choices=[('REGLEMENT', 'Règlement'), ('FORMULAIRE', 'Formulaire'), ('CIRCULAIRE', 'Circulaire'), ('AUTRE', 'Autre')], default='AUTRE', max_length=15)),
                ('fichier', models.FileField(upload_to='documents/')),
                ('est_public', models.BooleanField(default=True, help_text='Public = visible par tous. Privé = clubs affiliés uniquement.')),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_publies', to=settings.AUTH_USER_MODEL)),
                ('ligue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ligues.ligue')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-date_publication'],
            },
        ),
    ]
