# Generated by Django 6.0.7 on 2026-07-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualite',
            name='est_public',
            field=models.BooleanField(default=True, help_text='Public = visible sans connexion. Privé = visible uniquement par les clubs et comptes connectés.'),
        ),
    ]
