# Generated by Django 6.0.6 on 2026-06-24 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ligues', '0002_alter_ligue_nom_ligue_alter_ligue_sigle'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeSportive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text='Ex : 2025-2026', max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOTUREE', 'Clôturée')], default='ACTIVE', max_length=10)),
                ('ligue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annees_sportives', to='ligues.ligue')),
            ],
            options={
                'verbose_name': 'Année sportive',
                'verbose_name_plural': 'Années sportives',
                'ordering': ['-date_debut'],
                'unique_together': {('ligue', 'libelle')},
            },
        ),
    ]
