# Generated by Django 6.0.6 on 2026-06-24 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('practitioners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubrique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Rubrique',
                'verbose_name_plural': 'Rubriques',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='SessionExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Ex : Examen Mai 2026', max_length=200)),
                ('date_examen', models.DateField()),
                ('lieu', models.CharField(max_length=200)),
                ('date_ouverture_inscriptions', models.DateField()),
                ('date_cloture_inscriptions', models.DateField()),
                ('statut', models.CharField(choices=[('EN_PREPARATION', 'En préparation'), ('INSCRIPTIONS_OUVERTES', 'Inscriptions ouvertes'), ('INSCRIPTIONS_CLOSES', 'Inscriptions closes'), ('EN_COURS', 'En cours'), ('CLOTUREE', 'Clôturée'), ('RESULTATS_PUBLIES', 'Résultats publiés')], default='EN_PREPARATION', max_length=30)),
                ('annee_sportive', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='exams.anneesportive')),
            ],
            options={
                'verbose_name': "Session d'examen",
                'verbose_name_plural': "Sessions d'examen",
                'ordering': ['-date_examen'],
            },
        ),
        migrations.CreateModel(
            name='RubriqueGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.PositiveSmallIntegerField(default=1)),
                ('note_minimale', models.DecimalField(decimal_places=2, default=10, help_text='Note minimale sur 20 pour valider cette épreuve', max_digits=4)),
                ('actif', models.BooleanField(default=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rubrique_grades', to='practitioners.grade')),
                ('rubrique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rubrique_grades', to='exams.rubrique')),
            ],
            options={
                'verbose_name': 'Rubrique par grade',
                'verbose_name_plural': 'Rubriques par grade',
                'ordering': ['grade__ordre', 'rubrique__nom'],
                'unique_together': {('rubrique', 'grade')},
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, default=0, help_text='Calculé automatiquement depuis le tarif du grade visé', max_digits=10)),
                ('statut', models.CharField(choices=[('EN_ATTENTE_PAIEMENT', 'En attente de paiement'), ('PAIEMENT_VALIDE', 'Paiement validé'), ('AUTORISE', 'Autorisé à participer'), ('EXCLU', 'Exclu')], default='EN_ATTENTE_PAIEMENT', max_length=25)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('grade_vise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions', to='practitioners.grade')),
                ('pratiquant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions', to='practitioners.pratiquant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions', to='exams.sessionexamen')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['pratiquant__nom'],
                'unique_together': {('session', 'pratiquant')},
            },
        ),
        migrations.CreateModel(
            name='AffectationJury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_affectation', models.DateTimeField(auto_now_add=True)),
                ('jury', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations_jury', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_jury', to='exams.sessionexamen')),
            ],
            options={
                'verbose_name': 'Affectation jury',
                'verbose_name_plural': 'Affectations jury',
                'unique_together': {('session', 'jury')},
            },
        ),
        migrations.CreateModel(
            name='TarifExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, help_text='Montant en FCFA', max_digits=10)),
                ('annee_sportive', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifs', to='exams.anneesportive')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifs', to='practitioners.grade')),
            ],
            options={
                'verbose_name': "Tarif d'examen",
                'verbose_name_plural': "Tarifs d'examen",
                'ordering': ['annee_sportive', 'grade__ordre'],
                'unique_together': {('annee_sportive', 'grade')},
            },
        ),
    ]
