# Generated by Django 6.0.6 on 2026-06-27 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_rubrique_sessionexamen_rubriquegrade_inscription_and_more'),
        ('ligues', '0005_membreorganigramme_date_debut_fonction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeleMatricule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefixe', models.CharField(help_text='Sigle de la ligue, ex : LK', max_length=10)),
                ('derniere_sequence', models.PositiveIntegerField(default=0)),
                ('ligue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='modele_matricule', to='ligues.ligue')),
            ],
            options={
                'verbose_name': 'Modèle de matricule',
                'verbose_name_plural': 'Modèles de matricule',
            },
        ),
        migrations.CreateModel(
            name='OptionExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('actif', models.BooleanField(default=True)),
                ('ligue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options_examen', to='ligues.ligue')),
            ],
            options={
                'verbose_name': "Option d'examen",
                'verbose_name_plural': "Options d'examen",
                'ordering': ['nom'],
                'unique_together': {('ligue', 'nom')},
            },
        ),
        migrations.AddField(
            model_name='inscription',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions', to='exams.optionexamen'),
        ),
    ]
