# Generated by Django 6.0.6 on 2026-06-29 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_modelematricule_optionexamen_inscription_option'),
        ('ligues', '0005_membreorganigramme_date_debut_fonction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rubriquegrade',
            options={'ordering': [models.OrderBy(models.F('grade__ordre'), nulls_last=True), 'rubrique__nom'], 'verbose_name': 'Rubrique par grade', 'verbose_name_plural': 'Rubriques par grade'},
        ),
        migrations.AlterModelOptions(
            name='tarifexamen',
            options={'ordering': ['annee_sportive', models.OrderBy(models.F('grade__ordre'), nulls_last=True)], 'verbose_name': "Tarif d'examen", 'verbose_name_plural': "Tarifs d'examen"},
        ),
        migrations.CreateModel(
            name='ParametresExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pourcentage_ligue', models.DecimalField(decimal_places=2, default=25, help_text="Pourcentage des droits d'examen reversé à la ligue (ex : 25 → le GC paie 25 % du total)", max_digits=5)),
                ('ligue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametres_examen', to='ligues.ligue')),
            ],
            options={
                'verbose_name': "Paramètres d'examen",
                'verbose_name_plural': "Paramètres d'examen",
            },
        ),
    ]
