# Generated by Django 6.0.6 on 2026-06-29 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_alter_rubriquegrade_options_and_more'),
        ('practitioners', '0008_add_date_limite_paiement_cascade_inscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionexamen',
            name='date_limite_paiement',
            field=models.DateField(blank=True, help_text="Date limite pour compléter ou régulariser le paiement des droits d'examen", null=True),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='pratiquant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='practitioners.pratiquant'),
        ),
    ]
