# Generated by Django 6.0.6 on 2026-06-29 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_add_date_limite_paiement_cascade_inscription'),
        ('practitioners', '0010_grade_actuel_set_null'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rubriquegrade',
            options={'ordering': ['grade__id_grade', 'rubrique__nom'], 'verbose_name': 'Rubrique par grade', 'verbose_name_plural': 'Rubriques par grade'},
        ),
        migrations.AlterModelOptions(
            name='tarifexamen',
            options={'ordering': ['annee_sportive', 'grade__id_grade'], 'verbose_name': "Tarif d'examen", 'verbose_name_plural': "Tarifs d'examen"},
        ),
        migrations.AlterField(
            model_name='rubriquegrade',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubrique_grades', to='practitioners.grade'),
        ),
        migrations.AlterField(
            model_name='tarifexamen',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs', to='practitioners.grade'),
        ),
    ]
