# Generated by Django 6.0.6 on 2026-07-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_grade_fk_cascade'),
        ('practitioners', '0010_grade_actuel_set_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectationjury',
            name='grades',
            field=models.ManyToManyField(blank=True, related_name='affectations_jury', to='practitioners.grade', verbose_name='Grades à évaluer'),
        ),
        migrations.AddField(
            model_name='affectationjury',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='affectations_jury', to='exams.optionexamen', verbose_name='Options à évaluer'),
        ),
        migrations.AddField(
            model_name='affectationjury',
            name='rubriques',
            field=models.ManyToManyField(blank=True, related_name='affectations_jury', to='exams.rubrique', verbose_name='Rubriques à évaluer'),
        ),
    ]
