# Generated by Django 6.0.6 on 2026-07-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_affectation_jury_grades_options_rubriques'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='bulletin',
            field=models.FileField(blank=True, null=True, upload_to='bulletins_inscription/', verbose_name='Bulletin du grade actuel'),
        ),
    ]
