# Generated by Django 6.0.6 on 2026-07-01 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_inscription_bulletin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='bulletin',
        ),
    ]
