# Generated by Django 6.0.6 on 2026-07-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_remove_bulletin_inscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='motif_exclusion',
            field=models.TextField(blank=True, help_text="Raison de l'exclusion communiquée au club", verbose_name="Motif d'exclusion"),
        ),
    ]
