# Generated by Django 6.0.6 on 2026-07-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_inscription_option_obligatoire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubriquegrade',
            name='note_minimale',
            field=models.DecimalField(decimal_places=2, default=3, help_text='Note minimale sur 5 pour valider cette épreuve', max_digits=4),
        ),
    ]
