# Generated by Django 6.0.7 on 2026-08-04 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_alter_rubriquegrade_note_minimale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscription',
            options={'ordering': ['grade_vise__id_grade', 'pratiquant__nom', 'pratiquant__prenom'], 'verbose_name': 'Inscription', 'verbose_name_plural': 'Inscriptions'},
        ),
    ]
