# Generated by Django 6.0.7 on 2026-08-06 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0013_alter_inscription_options'),
        ('ligues', '0007_membreorganigramme_club_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnonceExamenPrevisionnelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Ex: Prochain Passage de Grade — Ceintures & Duans', max_length=200)),
                ('periode_prevue', models.CharField(help_text='Ex: Mi-Novembre 2026', max_length=150)),
                ('lieu_prevu', models.CharField(help_text='Ex: Palais des Sports de Ouagadougou 2000', max_length=200)),
                ('periode_inscriptions', models.CharField(help_text='Ex: Du 1er au 31 Octobre 2026', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Informations et consignes complémentaires pour les pratiquants et présidents de club.')),
                ('est_actif', models.BooleanField(default=True, help_text='Cocher pour afficher cette annonce sur le site public.')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('ligue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces_examens', to='ligues.ligue')),
            ],
            options={
                'verbose_name': "Annonce prévisionnelle d'examen",
                'verbose_name_plural': "Annonces prévisionnelles d'examens",
                'ordering': ['-date_creation'],
            },
        ),
    ]
