# Generated by Django 6.0.6 on 2026-08-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0014_annonceexamenprevisionnelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectationjury',
            name='rubrique_grades',
            field=models.ManyToManyField(blank=True, related_name='affectations_jury', to='exams.rubriquegrade', verbose_name='Épreuves (Grade + Rubrique) à évaluer'),
        ),
        migrations.AlterField(
            model_name='annonceexamenprevisionnelle',
            name='description',
            field=models.TextField(blank=True, help_text='Informations et consignes complémentaires pour les licenciés et présidents de club.'),
        ),
    ]
