# Generated by Django 4.2.30 on 2026-09-21 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0015_affectationjury_rubrique_grades_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoSessionExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos_examens/%Y/%m/', verbose_name="Photo de l'examen")),
                ('legende', models.CharField(blank=True, help_text='Courte description ou commentaire sur la photo', max_length=255, verbose_name='Légende / Commentaire')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('ajoute_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='exams.sessionexamen')),
            ],
            options={
                'verbose_name': "Photo d'examen",
                'verbose_name_plural': "Photos d'examens",
                'ordering': ['ordre', '-date_ajout'],
            },
        ),
    ]
