# Generated by Django 4.2.30 on 2026-09-22 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("exams", "0016_photosessionexamen"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="photosessionexamen",
            options={
                "ordering": ["ordre", "-date_ajout"],
                "verbose_name": "Photo d'album",
                "verbose_name_plural": "Photos d'albums",
            },
        ),
        migrations.AlterField(
            model_name="photosessionexamen",
            name="image",
            field=models.ImageField(
                upload_to="photos_examens/%Y/%m/", verbose_name="Photo de l'album"
            ),
        ),
        migrations.AlterField(
            model_name="photosessionexamen",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="exams.sessionexamen",
                verbose_name="Session d'examen (optionnel)",
            ),
        ),
        migrations.CreateModel(
            name="AlbumPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titre",
                    models.CharField(max_length=200, verbose_name="Titre de l'album"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Présentation générale de l'album photo",
                        verbose_name="Description / Légende globale",
                    ),
                ),
                (
                    "date_evenement",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de l'événement",
                    ),
                ),
                (
                    "couverture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="albums/couvertures/%Y/%m/",
                        verbose_name="Image de couverture",
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session_examen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="albums",
                        to="exams.sessionexamen",
                        verbose_name="Session d'examen associée (optionnel)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Album photo",
                "verbose_name_plural": "Albums photos",
                "ordering": ["-date_evenement", "-date_creation"],
            },
        ),
        migrations.AddField(
            model_name="photosessionexamen",
            name="album",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="exams.albumphoto",
                verbose_name="Album photo",
            ),
        ),
    ]
