# Generated by Django 4.2.30 on 2026-09-23 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0017_alter_photosessionexamen_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumphoto',
            name='session_examen',
        ),
        migrations.AddField(
            model_name='albumphoto',
            name='annee_sportive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='exams.anneesportive', verbose_name='Année sportive associée (optionnel)'),
        ),
    ]
