# Generated by Django 4.2.30 on 2026-09-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0018_remove_albumphoto_session_examen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumphoto',
            name='type_evenement',
            field=models.CharField(choices=[('EXAMEN', 'Passage de Grade / Examen'), ('COMPETITION', 'Compétition / Championnat'), ('STAGE', 'Stage / Entraînement'), ('CEREMONIE', 'Cérémonie & Événement'), ('GALERIE', 'Galerie Générale')], default='GALERIE', max_length=50, verbose_name="Type d'événement"),
        ),
    ]
