# Generated by Django 4.2.30 on 2026-09-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0019_albumphoto_type_evenement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumphoto',
            name='type_evenement',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name="Type d'événement"),
        ),
    ]
